name: C/C++ CI

on:
  push:
    # branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
    # - uses: conda-incubator/setup-miniconda@v3
      # with:
      #   auto-activate-base: true
      #   activate-environment: ""
    - name: Install Dependencies
      run: |
           sudo apt-get update
           sudo apt update
           sudo apt install -y cmake libeigen3-dev  python3-pip libboost-all-dev libfcl-dev libyaml-cpp-dev

    # - uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-update-conda: true
    #     python-version: "3.11"
    # - run: conda --version
    # - run: which python
    # - name: Install Pinocchio
    #   run: conda install -c conda-forge pinocchio=2.6.10
    # - name: Conda info
    #   shell: bash -el {0}
    #   run: conda info
    # - name: Conda list
    #   shell: pwsh
    #   run: conda list





    - name: Install Pinocchio
      run: |
           sudo apt install -qqy lsb-release curl
           sudo mkdir -p /etc/apt/keyrings
           curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc \
               | sudo tee /etc/apt/keyrings/robotpkg.asc
           echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" \
                 | sudo tee /etc/apt/sources.list.d/robotpkg.list

           sudo apt update
           sudo apt install -qqy robotpkg-py310-pinocchio

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Run CMake
      run: |
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=ON -DBUILD_DYNOBENCH=ON -DBUILD_PYRRT=ON -DBUILD_BENCHMARK=OFF -DCMAKE_PREFIX_PATH="/opt/openrobots/"   ..

    - name: Make
      run: |
           cd build
           make
    - name: C++ tests
      run: |
           cd build && make && ./test_dynorrt  -- ../ _deps/dynobench-src/

    - name: Check 1 Python Bindings
      run: |
           cd build/bindings/python
           python3 -c 'import pydynorrt'
    - name: Build and Install Python Package
      run: |
           pip3 install .
           python3 -c 'import pydynorrt'


    - name: Python Install Dependencies
      run: |
           pip3 install numpy
           pip3 install matplotlib
    - name: Examples Python
      run: |
           PYTHONPATH="build/bindings/python/" python3  test_rrt.py
    - name: C++ with Python visualization
      run: |
           PYTHONPATH="build/bindings/python/" python3  plot.py

    - name: Python with Pinocchio
      run:  |
          pip3 install pin example-robot-data meshcat scipy tqdm
          PYTHONPATH="build/bindings/python/" python3 examplesPIN/my_rrt.py
          PYTHONPATH="build/bindings/python/" python3 examplesPIN/my_rrt2.py
