name: CI


on:
  push:
  pull_request:
    branches: [ "main","dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12  # You can specify the Python version you need
        activate-environment: myenv  # Name of the conda environment
        auto-update-conda: true
        auto-activate-base: true


    - name: Create environment
      run: conda create --name myenv python=3.12

    - run: |
        conda info
        conda list


    - name: Install dependencies
      run: |
        conda init
        conda activate myenv
        conda install -y pinocchio numpy cmake make cxx-compiler  -c conda-forge  # Replace with your specific dependencies
        # If you need to install packages from a requirements.txt file
        # conda install --file requirements.txt

    - name: Compile package
      run: |
        conda init
        conda activate myenv
        # Add commands to compile your package
        # For example, if using cmake:
        mkdir build
        cd build
        cmake ..
        make

