name: C/C++ CI

on:
  push:
    # branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
    # - uses: conda-incubator/setup-miniconda@v3
      # with:
      #   auto-activate-base: true
      #   activate-environment: ""
    - name: Install Dependencies in latest ubuntu
      run: |
           sudo apt-get update
           sudo apt update
           sudo apt install -y cmake libeigen3-dev  python3-pip libboost-all-dev libfcl-dev libyaml-cpp-dev

    # - uses: conda-incubator/setup-miniconda@v3
    #   with:
    #     auto-update-conda: true
    #     python-version: "3.11"
    # - run: conda --version
    # - run: which python
    # - name: Install Pinocchio
    #   run: conda install -c conda-forge pinocchio=2.6.10
    # - name: Conda info
    #   shell: bash -el {0}
    #   run: conda info
    # - name: Conda list
    #   shell: pwsh
    #   run: conda list





    - name: Install Pinocchio
      run: |
           sudo apt install -qqy lsb-release curl
           sudo mkdir -p /etc/apt/keyrings
           curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc \
               | sudo tee /etc/apt/keyrings/robotpkg.asc
           echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" \
                 | sudo tee /etc/apt/sources.list.d/robotpkg.list

           sudo apt update
           sudo apt install -qqy robotpkg-py310-pinocchio

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Run CMake
      run: |
          mkdir build
          cd build
          cmake -DBUILD_EXAMPLES=ON -DBUILD_DYNOBENCH=ON -DBUILD_PYRRT=ON -DBUILD_BENCHMARK=OFF -DCMAKE_PREFIX_PATH="/opt/openrobots/"   -DBUILD_TESTS_RRT=1 -DPIN_PYTHON_OBJECT=1 ..
    - name: Make
      run: |
           cd build
           make
    - name: C++ tests
      run: |
           cd build
           ./test_main  -- ../ _deps/dynobench-src/
           ./test_pin -- ../ _deps/dynobench-src/
           ./test_dyno -- ../ _deps/dynobench-src/

    - name: Python Install Dependencies
      run: |
           pip install numpy matplotlib meshcat scipy tqdm

    - name: Check Compiled Python Bindings
      run: |
           cd build/bindings/python
           PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages python -c 'import pydynorrt'

    # - name: Build and Install Python Package
    #   run: |
    #        CMAKE_PREFIX_PATH=/opt/openrobots/ pip3 install .
    #        python3 -c 'import pydynorrt'


    - name: Install Python Package into system
      run: |
           sudo cmake --install build
           python -c "import pydynorrt"


    - name: Test in Python
      # NOTE: I need to update PYTHONPATH because of Pinocchio from APT
      run: |
           PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages python -m unittest pydynorrt.test.test_cols
           PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages python -m unittest pydynorrt.test.test_ik
           PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages python -m unittest pydynorrt.test.test_basic

    - name: Examples Python
      run: |
           # NOTE: I need to update PYTHONPATH because of Pinocchio from APT
           PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages  python3  examples/test_rrt.py

    - name: C++ with Python visualization
      run: |
           # NOTE: I need to update PYTHONPATH because of Pinocchio from APT
           PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages  python3  examples/plot.py

    - name: Python with Pinocchio
      run:  |
          # NOTE: I need to update PYTHONPATH because of Pinocchio from APT
          PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages  python3 examplesPIN/my_rrt.py
          PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages  python3 examples/play_kuka.py

    - name: Run Notebook
      run: |
          # NOTE: I need to update PYTHONPATH because of Pinocchio from APT
          PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages python3 notebooks/tutorial0.py

    - name: Example CPP project that depends on this package
      run: |
          cd example_cpplib
          cmake -S . -B build -DCMAKE_PREFIX_PATH="/opt/openrobots/"
          cmake --build build
          ./build/main
          ./build/main_pin ../
